const gitHubResponse = """

{
  "total_count": 26636,
  "incomplete_results": false,
  "items": [
    {
      "login": "felipe",
      "id": 420001,
      "node_id": "MDQ6VXNlcjQyMDAwMQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/420001?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipe",
      "html_url": "https://github.com/felipe",
      "followers_url": "https://api.github.com/users/felipe/followers",
      "following_url": "https://api.github.com/users/felipe/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipe/subscriptions",
      "organizations_url": "https://api.github.com/users/felipe/orgs",
      "repos_url": "https://api.github.com/users/felipe/repos",
      "events_url": "https://api.github.com/users/felipe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipe/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipefialho",
      "id": 3603793,
      "node_id": "MDQ6VXNlcjM2MDM3OTM=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/3603793?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipefialho",
      "html_url": "https://github.com/felipefialho",
      "followers_url": "https://api.github.com/users/felipefialho/followers",
      "following_url": "https://api.github.com/users/felipefialho/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipefialho/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipefialho/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipefialho/subscriptions",
      "organizations_url": "https://api.github.com/users/felipefialho/orgs",
      "repos_url": "https://api.github.com/users/felipefialho/repos",
      "events_url": "https://api.github.com/users/felipefialho/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipefialho/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipecsl",
      "id": 190648,
      "node_id": "MDQ6VXNlcjE5MDY0OA==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/190648?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipecsl",
      "html_url": "https://github.com/felipecsl",
      "followers_url": "https://api.github.com/users/felipecsl/followers",
      "following_url": "https://api.github.com/users/felipecsl/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipecsl/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipecsl/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipecsl/subscriptions",
      "organizations_url": "https://api.github.com/users/felipecsl/orgs",
      "repos_url": "https://api.github.com/users/felipecsl/repos",
      "events_url": "https://api.github.com/users/felipecsl/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipecsl/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipenmoura",
      "id": 347387,
      "node_id": "MDQ6VXNlcjM0NzM4Nw==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/347387?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipenmoura",
      "html_url": "https://github.com/felipenmoura",
      "followers_url": "https://api.github.com/users/felipenmoura/followers",
      "following_url": "https://api.github.com/users/felipenmoura/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipenmoura/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipenmoura/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipenmoura/subscriptions",
      "organizations_url": "https://api.github.com/users/felipenmoura/orgs",
      "repos_url": "https://api.github.com/users/felipenmoura/repos",
      "events_url": "https://api.github.com/users/felipenmoura/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipenmoura/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipernb",
      "id": 227059,
      "node_id": "MDQ6VXNlcjIyNzA1OQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/227059?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipernb",
      "html_url": "https://github.com/felipernb",
      "followers_url": "https://api.github.com/users/felipernb/followers",
      "following_url": "https://api.github.com/users/felipernb/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipernb/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipernb/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipernb/subscriptions",
      "organizations_url": "https://api.github.com/users/felipernb/orgs",
      "repos_url": "https://api.github.com/users/felipernb/repos",
      "events_url": "https://api.github.com/users/felipernb/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipernb/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipeweb",
      "id": 4874009,
      "node_id": "MDQ6VXNlcjQ4NzQwMDk=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/4874009?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipeweb",
      "html_url": "https://github.com/felipeweb",
      "followers_url": "https://api.github.com/users/felipeweb/followers",
      "following_url": "https://api.github.com/users/felipeweb/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipeweb/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipeweb/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipeweb/subscriptions",
      "organizations_url": "https://api.github.com/users/felipeweb/orgs",
      "repos_url": "https://api.github.com/users/felipeweb/repos",
      "events_url": "https://api.github.com/users/felipeweb/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipeweb/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipesanches",
      "id": 213676,
      "node_id": "MDQ6VXNlcjIxMzY3Ng==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/213676?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipesanches",
      "html_url": "https://github.com/felipesanches",
      "followers_url": "https://api.github.com/users/felipesanches/followers",
      "following_url": "https://api.github.com/users/felipesanches/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipesanches/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipesanches/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipesanches/subscriptions",
      "organizations_url": "https://api.github.com/users/felipesanches/orgs",
      "repos_url": "https://api.github.com/users/felipesanches/repos",
      "events_url": "https://api.github.com/users/felipesanches/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipesanches/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipesousa",
      "id": 8076640,
      "node_id": "MDQ6VXNlcjgwNzY2NDA=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/8076640?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipesousa",
      "html_url": "https://github.com/felipesousa",
      "followers_url": "https://api.github.com/users/felipesousa/followers",
      "following_url": "https://api.github.com/users/felipesousa/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipesousa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipesousa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipesousa/subscriptions",
      "organizations_url": "https://api.github.com/users/felipesousa/orgs",
      "repos_url": "https://api.github.com/users/felipesousa/repos",
      "events_url": "https://api.github.com/users/felipesousa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipesousa/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipecruz",
      "id": 84613,
      "node_id": "MDQ6VXNlcjg0NjEz",
      "avatar_url": "https://avatars3.githubusercontent.com/u/84613?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipecruz",
      "html_url": "https://github.com/felipecruz",
      "followers_url": "https://api.github.com/users/felipecruz/followers",
      "following_url": "https://api.github.com/users/felipecruz/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipecruz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipecruz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipecruz/subscriptions",
      "organizations_url": "https://api.github.com/users/felipecruz/orgs",
      "repos_url": "https://api.github.com/users/felipecruz/repos",
      "events_url": "https://api.github.com/users/felipecruz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipecruz/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipec",
      "id": 8358,
      "node_id": "MDQ6VXNlcjgzNTg=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/8358?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipec",
      "html_url": "https://github.com/felipec",
      "followers_url": "https://api.github.com/users/felipec/followers",
      "following_url": "https://api.github.com/users/felipec/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipec/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipec/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipec/subscriptions",
      "organizations_url": "https://api.github.com/users/felipec/orgs",
      "repos_url": "https://api.github.com/users/felipec/repos",
      "events_url": "https://api.github.com/users/felipec/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipec/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipeg48",
      "id": 655019,
      "node_id": "MDQ6VXNlcjY1NTAxOQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/655019?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipeg48",
      "html_url": "https://github.com/felipeg48",
      "followers_url": "https://api.github.com/users/felipeg48/followers",
      "following_url": "https://api.github.com/users/felipeg48/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipeg48/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipeg48/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipeg48/subscriptions",
      "organizations_url": "https://api.github.com/users/felipeg48/orgs",
      "repos_url": "https://api.github.com/users/felipeg48/repos",
      "events_url": "https://api.github.com/users/felipeg48/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipeg48/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipensp",
      "id": 773947,
      "node_id": "MDQ6VXNlcjc3Mzk0Nw==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/773947?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipensp",
      "html_url": "https://github.com/felipensp",
      "followers_url": "https://api.github.com/users/felipensp/followers",
      "following_url": "https://api.github.com/users/felipensp/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipensp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipensp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipensp/subscriptions",
      "organizations_url": "https://api.github.com/users/felipensp/orgs",
      "repos_url": "https://api.github.com/users/felipensp/repos",
      "events_url": "https://api.github.com/users/felipensp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipensp/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "M3nin0",
      "id": 17037029,
      "node_id": "MDQ6VXNlcjE3MDM3MDI5",
      "avatar_url": "https://avatars2.githubusercontent.com/u/17037029?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/M3nin0",
      "html_url": "https://github.com/M3nin0",
      "followers_url": "https://api.github.com/users/M3nin0/followers",
      "following_url": "https://api.github.com/users/M3nin0/following{/other_user}",
      "gists_url": "https://api.github.com/users/M3nin0/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/M3nin0/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/M3nin0/subscriptions",
      "organizations_url": "https://api.github.com/users/M3nin0/orgs",
      "repos_url": "https://api.github.com/users/M3nin0/repos",
      "events_url": "https://api.github.com/users/M3nin0/events{/privacy}",
      "received_events_url": "https://api.github.com/users/M3nin0/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipemfp",
      "id": 8146112,
      "node_id": "MDQ6VXNlcjgxNDYxMTI=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/8146112?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipemfp",
      "html_url": "https://github.com/felipemfp",
      "followers_url": "https://api.github.com/users/felipemfp/followers",
      "following_url": "https://api.github.com/users/felipemfp/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipemfp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipemfp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipemfp/subscriptions",
      "organizations_url": "https://api.github.com/users/felipemfp/orgs",
      "repos_url": "https://api.github.com/users/felipemfp/repos",
      "events_url": "https://api.github.com/users/felipemfp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipemfp/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Scrxtchy",
      "id": 12771982,
      "node_id": "MDQ6VXNlcjEyNzcxOTgy",
      "avatar_url": "https://avatars2.githubusercontent.com/u/12771982?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Scrxtchy",
      "html_url": "https://github.com/Scrxtchy",
      "followers_url": "https://api.github.com/users/Scrxtchy/followers",
      "following_url": "https://api.github.com/users/Scrxtchy/following{/other_user}",
      "gists_url": "https://api.github.com/users/Scrxtchy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Scrxtchy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Scrxtchy/subscriptions",
      "organizations_url": "https://api.github.com/users/Scrxtchy/orgs",
      "repos_url": "https://api.github.com/users/Scrxtchy/repos",
      "events_url": "https://api.github.com/users/Scrxtchy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Scrxtchy/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipecastrosales",
      "id": 59374587,
      "node_id": "MDQ6VXNlcjU5Mzc0NTg3",
      "avatar_url": "https://avatars3.githubusercontent.com/u/59374587?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipecastrosales",
      "html_url": "https://github.com/felipecastrosales",
      "followers_url": "https://api.github.com/users/felipecastrosales/followers",
      "following_url": "https://api.github.com/users/felipecastrosales/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipecastrosales/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipecastrosales/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipecastrosales/subscriptions",
      "organizations_url": "https://api.github.com/users/felipecastrosales/orgs",
      "repos_url": "https://api.github.com/users/felipecastrosales/repos",
      "events_url": "https://api.github.com/users/felipecastrosales/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipecastrosales/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "zimmerle",
      "id": 428268,
      "node_id": "MDQ6VXNlcjQyODI2OA==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/428268?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zimmerle",
      "html_url": "https://github.com/zimmerle",
      "followers_url": "https://api.github.com/users/zimmerle/followers",
      "following_url": "https://api.github.com/users/zimmerle/following{/other_user}",
      "gists_url": "https://api.github.com/users/zimmerle/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zimmerle/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zimmerle/subscriptions",
      "organizations_url": "https://api.github.com/users/zimmerle/orgs",
      "repos_url": "https://api.github.com/users/zimmerle/repos",
      "events_url": "https://api.github.com/users/zimmerle/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zimmerle/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipebernardes",
      "id": 7507797,
      "node_id": "MDQ6VXNlcjc1MDc3OTc=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/7507797?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipebernardes",
      "html_url": "https://github.com/felipebernardes",
      "followers_url": "https://api.github.com/users/felipebernardes/followers",
      "following_url": "https://api.github.com/users/felipebernardes/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipebernardes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipebernardes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipebernardes/subscriptions",
      "organizations_url": "https://api.github.com/users/felipebernardes/orgs",
      "repos_url": "https://api.github.com/users/felipebernardes/repos",
      "events_url": "https://api.github.com/users/felipebernardes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipebernardes/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipessalvatore",
      "id": 11237428,
      "node_id": "MDQ6VXNlcjExMjM3NDI4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/11237428?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipessalvatore",
      "html_url": "https://github.com/felipessalvatore",
      "followers_url": "https://api.github.com/users/felipessalvatore/followers",
      "following_url": "https://api.github.com/users/felipessalvatore/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipessalvatore/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipessalvatore/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipessalvatore/subscriptions",
      "organizations_url": "https://api.github.com/users/felipessalvatore/orgs",
      "repos_url": "https://api.github.com/users/felipessalvatore/repos",
      "events_url": "https://api.github.com/users/felipessalvatore/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipessalvatore/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipenoris",
      "id": 12482900,
      "node_id": "MDQ6VXNlcjEyNDgyOTAw",
      "avatar_url": "https://avatars2.githubusercontent.com/u/12482900?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipenoris",
      "html_url": "https://github.com/felipenoris",
      "followers_url": "https://api.github.com/users/felipenoris/followers",
      "following_url": "https://api.github.com/users/felipenoris/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipenoris/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipenoris/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipenoris/subscriptions",
      "organizations_url": "https://api.github.com/users/felipenoris/orgs",
      "repos_url": "https://api.github.com/users/felipenoris/repos",
      "events_url": "https://api.github.com/users/felipenoris/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipenoris/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipez3r0",
      "id": 7429615,
      "node_id": "MDQ6VXNlcjc0Mjk2MTU=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/7429615?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipez3r0",
      "html_url": "https://github.com/felipez3r0",
      "followers_url": "https://api.github.com/users/felipez3r0/followers",
      "following_url": "https://api.github.com/users/felipez3r0/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipez3r0/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipez3r0/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipez3r0/subscriptions",
      "organizations_url": "https://api.github.com/users/felipez3r0/orgs",
      "repos_url": "https://api.github.com/users/felipez3r0/repos",
      "events_url": "https://api.github.com/users/felipez3r0/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipez3r0/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipeorlando",
      "id": 6332116,
      "node_id": "MDQ6VXNlcjYzMzIxMTY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/6332116?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipeorlando",
      "html_url": "https://github.com/felipeorlando",
      "followers_url": "https://api.github.com/users/felipeorlando/followers",
      "following_url": "https://api.github.com/users/felipeorlando/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipeorlando/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipeorlando/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipeorlando/subscriptions",
      "organizations_url": "https://api.github.com/users/felipeorlando/orgs",
      "repos_url": "https://api.github.com/users/felipeorlando/repos",
      "events_url": "https://api.github.com/users/felipeorlando/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipeorlando/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipealfonsog",
      "id": 7793517,
      "node_id": "MDQ6VXNlcjc3OTM1MTc=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/7793517?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipealfonsog",
      "html_url": "https://github.com/felipealfonsog",
      "followers_url": "https://api.github.com/users/felipealfonsog/followers",
      "following_url": "https://api.github.com/users/felipealfonsog/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipealfonsog/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipealfonsog/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipealfonsog/subscriptions",
      "organizations_url": "https://api.github.com/users/felipealfonsog/orgs",
      "repos_url": "https://api.github.com/users/felipealfonsog/repos",
      "events_url": "https://api.github.com/users/felipealfonsog/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipealfonsog/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipealbuquerq",
      "id": 1964926,
      "node_id": "MDQ6VXNlcjE5NjQ5MjY=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1964926?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipealbuquerq",
      "html_url": "https://github.com/felipealbuquerq",
      "followers_url": "https://api.github.com/users/felipealbuquerq/followers",
      "following_url": "https://api.github.com/users/felipealbuquerq/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipealbuquerq/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipealbuquerq/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipealbuquerq/subscriptions",
      "organizations_url": "https://api.github.com/users/felipealbuquerq/orgs",
      "repos_url": "https://api.github.com/users/felipealbuquerq/repos",
      "events_url": "https://api.github.com/users/felipealbuquerq/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipealbuquerq/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "FelipeAdorno",
      "id": 4122823,
      "node_id": "MDQ6VXNlcjQxMjI4MjM=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/4122823?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/FelipeAdorno",
      "html_url": "https://github.com/FelipeAdorno",
      "followers_url": "https://api.github.com/users/FelipeAdorno/followers",
      "following_url": "https://api.github.com/users/FelipeAdorno/following{/other_user}",
      "gists_url": "https://api.github.com/users/FelipeAdorno/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/FelipeAdorno/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/FelipeAdorno/subscriptions",
      "organizations_url": "https://api.github.com/users/FelipeAdorno/orgs",
      "repos_url": "https://api.github.com/users/FelipeAdorno/repos",
      "events_url": "https://api.github.com/users/FelipeAdorno/events{/privacy}",
      "received_events_url": "https://api.github.com/users/FelipeAdorno/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "feliperazeek",
      "id": 440809,
      "node_id": "MDQ6VXNlcjQ0MDgwOQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/440809?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/feliperazeek",
      "html_url": "https://github.com/feliperazeek",
      "followers_url": "https://api.github.com/users/feliperazeek/followers",
      "following_url": "https://api.github.com/users/feliperazeek/following{/other_user}",
      "gists_url": "https://api.github.com/users/feliperazeek/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/feliperazeek/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/feliperazeek/subscriptions",
      "organizations_url": "https://api.github.com/users/feliperazeek/orgs",
      "repos_url": "https://api.github.com/users/feliperazeek/repos",
      "events_url": "https://api.github.com/users/feliperazeek/events{/privacy}",
      "received_events_url": "https://api.github.com/users/feliperazeek/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipe-augusto",
      "id": 9551950,
      "node_id": "MDQ6VXNlcjk1NTE5NTA=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/9551950?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipe-augusto",
      "html_url": "https://github.com/felipe-augusto",
      "followers_url": "https://api.github.com/users/felipe-augusto/followers",
      "following_url": "https://api.github.com/users/felipe-augusto/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipe-augusto/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipe-augusto/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipe-augusto/subscriptions",
      "organizations_url": "https://api.github.com/users/felipe-augusto/orgs",
      "repos_url": "https://api.github.com/users/felipe-augusto/repos",
      "events_url": "https://api.github.com/users/felipe-augusto/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipe-augusto/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipecode",
      "id": 4934673,
      "node_id": "MDQ6VXNlcjQ5MzQ2NzM=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/4934673?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipecode",
      "html_url": "https://github.com/felipecode",
      "followers_url": "https://api.github.com/users/felipecode/followers",
      "following_url": "https://api.github.com/users/felipecode/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipecode/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipecode/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipecode/subscriptions",
      "organizations_url": "https://api.github.com/users/felipecode/orgs",
      "repos_url": "https://api.github.com/users/felipecode/repos",
      "events_url": "https://api.github.com/users/felipecode/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipecode/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipefontoura",
      "id": 281622,
      "node_id": "MDQ6VXNlcjI4MTYyMg==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/281622?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipefontoura",
      "html_url": "https://github.com/felipefontoura",
      "followers_url": "https://api.github.com/users/felipefontoura/followers",
      "following_url": "https://api.github.com/users/felipefontoura/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipefontoura/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipefontoura/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipefontoura/subscriptions",
      "organizations_url": "https://api.github.com/users/felipefontoura/orgs",
      "repos_url": "https://api.github.com/users/felipefontoura/repos",
      "events_url": "https://api.github.com/users/felipefontoura/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipefontoura/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "felipealvessi",
      "id": 48339491,
      "node_id": "MDQ6VXNlcjQ4MzM5NDkx",
      "avatar_url": "https://avatars0.githubusercontent.com/u/48339491?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felipealvessi",
      "html_url": "https://github.com/felipealvessi",
      "followers_url": "https://api.github.com/users/felipealvessi/followers",
      "following_url": "https://api.github.com/users/felipealvessi/following{/other_user}",
      "gists_url": "https://api.github.com/users/felipealvessi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felipealvessi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felipealvessi/subscriptions",
      "organizations_url": "https://api.github.com/users/felipealvessi/orgs",
      "repos_url": "https://api.github.com/users/felipealvessi/repos",
      "events_url": "https://api.github.com/users/felipealvessi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felipealvessi/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}


""";
